version: '3'

services:
  mosquitto:
    build:
      context: ./mosquitto
      dockerfile: ./Dockerfile
    container_name: mosquitto
    depends_on:
      - postgres_db
    links:
      - postgres_db
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    command: ['mosquitto', '-c', '/mosquitto/config/mosquitto.conf']
    ports:
      - 1883:1883

  postgres_db:
    build: 
      context: ./postgres_db
      dockerfile: ./Dockerfile
    container_name: postgres_db
    environment:
      POSTGRES_DB: mosquitto
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_password
    volumes:
      - ./postgres_db/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - 5432:5432
    healthcheck:
     test: ["CMD-SHELL", "pg_isready -U root -d mosquitto"]
     interval: 5s
     timeout: 3s
     retries: 5

